import {beforeEach,describe,expect,it,vi} from'vitest';
import {DdnsUpdateUseCase} from'../src/application/ddns-update';import type{Client,UpdateLog}from'../src/domain/models';import type{ClientRepository}from'../src/repositories/client-repository';import type{CloudflareDnsService,DnsRecord}from'../src/services/cloudflare-dns-service';import{hashToken}from'../src/services/token-service';
const rawToken=`ddns_${'x'.repeat(32)}`;let client:Client;let logs:UpdateLog[];let status:unknown;
function repository():ClientRepository{return{list:vi.fn(),findById:vi.fn(),findBySlug:vi.fn(async()=>client),create:vi.fn(),update:vi.fn(),setEnabled:vi.fn(),rotateToken:vi.fn(),updateStatus:vi.fn(async(_id,value)=>{status=value;}),remove:vi.fn(),addLog:vi.fn(async log=>{logs.push(log);}),logs:vi.fn(),audit:vi.fn(),dashboard:vi.fn()};}
function dns(content='1.1.1.1'){const record:DnsRecord={id:'record',zoneId:'zone',zoneName:'example.com',name:'home.example.com',type:'A',content,ttl:1};return{getRecord:vi.fn(async()=>record),update:vi.fn(async()=>undefined)} as unknown as CloudflareDnsService;}
const request=(token=rawToken,ip='8.8.8.8')=>new Request('https://ddns.example.com/api/ddns/home',{method:'POST',headers:{Authorization:`Bearer ${token}`,'CF-Connecting-IP':ip}});
beforeEach(async()=>{logs=[];status=null;client={id:'client',displayName:'Home',slug:'home',enabled:true,zoneId:'zone',zoneName:'example.com',recordId:'record',recordName:'home.example.com',recordType:'A',tokenHash:await hashToken(rawToken),tokenCreatedAt:'now',lastIp:null,lastSourceIp:null,lastStatus:null,lastUpdatedAt:null,createdAt:'now',updatedAt:'now'};});
describe('DDNS update use case',()=>{
  it('updates only the bound record and audits it',async()=>{const api=dns();const limiter=vi.fn(async()=>undefined);const result=await new DdnsUpdateUseCase(repository(),api,false,limiter).execute('home',request());expect(result.updated).toBe(true);expect(api.update).toHaveBeenCalledWith(expect.objectContaining({id:'record'}),'8.8.8.8');expect(limiter).toHaveBeenCalledWith('client');expect(logs[0]).toMatchObject({oldIp:'1.1.1.1',newIp:'8.8.8.8',updated:true,status:'updated'});expect(status).toMatchObject({sourceIp:'8.8.8.8'});});
  it('does not update an unchanged record',async()=>{const api=dns('8.8.8.8');expect((await new DdnsUpdateUseCase(repository(),api,false).execute('home',request())).updated).toBe(false);expect(api.update).not.toHaveBeenCalled();expect(logs[0]?.status).toBe('unchanged');});
  it('accepts a pre-parsed compatibility token without rewriting request headers',async()=>{const api=dns();const withoutAuthorization=new Request('https://ddns.example.com/api/compat/unifi/home',{headers:{'CF-Connecting-IP':'8.8.8.8'}});const result=await new DdnsUpdateUseCase(repository(),api,false).executeWithToken('home',withoutAuthorization,rawToken);expect(result).toMatchObject({updated:true,ip:'8.8.8.8'});});
  it('rejects missing, wrong, disabled, and private source credentials',async()=>{const limiter=vi.fn();await expect(new DdnsUpdateUseCase(repository(),dns(),false,limiter).execute('home',request('wrong-token-credential-value'))).rejects.toMatchObject({status:401});expect(limiter).not.toHaveBeenCalled();client.enabled=false;await expect(new DdnsUpdateUseCase(repository(),dns(),false).execute('home',request())).rejects.toMatchObject({status:403});client.enabled=true;await expect(new DdnsUpdateUseCase(repository(),dns(),false).execute('home',request(rawToken,'10.0.0.1'))).rejects.toMatchObject({status:400});});
  it('fails closed if Cloudflare returns a different binding',async()=>{const api=dns();vi.mocked(api.getRecord).mockResolvedValue({...await api.getRecord('zone','record'),name:'other.example.com'});await expect(new DdnsUpdateUseCase(repository(),api,false).execute('home',request())).rejects.toMatchObject({status:502});expect(logs[0]).toMatchObject({status:'failed',errorCode:'DNS_UPDATE_FAILED'});});
});
