import { describe,expect,it } from 'vitest';
import { AppError } from '../src/domain/errors';
import { basicCredentials,bearerToken,errorResponse,json,strictJson,success } from '../src/utils/http';
import { redact,securityHeaders } from '../src/utils/security';

describe('HTTP policy',()=>{
  it('accepts bearer only, never Basic',()=>{expect(bearerToken(new Request('https://x',{headers:{Authorization:`Bearer ddns_${'a'.repeat(32)}`}}))).toContain('ddns_');expect(bearerToken(new Request('https://x',{headers:{Authorization:'Basic abc'}}))).toBeNull();expect(bearerToken(new Request('https://x'))).toBeNull();});
  it('parses strict UniFi Basic credentials without accepting malformed values',()=>{const password=`ddns_${'a'.repeat(32)}`;const valid=new Request('https://x',{headers:{Authorization:`Basic ${btoa(`linhome:${password}`)}`}});expect(basicCredentials(valid)).toEqual({username:'linhome',password});expect(basicCredentials(new Request('https://x',{headers:{Authorization:`Basic ${btoa(`../admin:${password}`)}`}}))).toBeNull();expect(basicCredentials(new Request('https://x',{headers:{Authorization:'Basic !!!'}}))).toBeNull();expect(basicCredentials(new Request('https://x',{headers:{Authorization:`Basic ${btoa('missing-colon')}`}}))).toBeNull();});
  it('parses only bounded JSON',async()=>{expect(await strictJson<{ok:boolean}>(new Request('https://x',{method:'POST',headers:{'Content-Type':'application/json; charset=utf-8'},body:'{"ok":true}'}))).toEqual({ok:true});await expect(strictJson(new Request('https://x',{method:'POST',body:'{}'}))).rejects.toMatchObject({status:415});await expect(strictJson(new Request('https://x',{method:'POST',headers:{'Content-Type':'application/json','Content-Length':'20000'},body:'{}'}))).rejects.toMatchObject({status:413});await expect(strictJson(new Request('https://x',{method:'POST',headers:{'Content-Type':'application/json'},body:'x'}))).rejects.toMatchObject({status:400});});
  it('uses stable envelopes and hides internal errors',async()=>{expect(await json({a:1}).json()).toEqual({a:1});expect(await success({a:1}).json()).toEqual({success:true,data:{a:1}});expect(await errorResponse(new AppError(401,'Unauthorized','X')).json()).toEqual({success:false,message:'Unauthorized'});expect(await errorResponse(new Error('sql leaked')).json()).toEqual({success:false,message:'Internal server error'});expect(await errorResponse(new Error('detail'),true).json()).toEqual({success:false,message:'detail'});});
  it('sets every browser security header without unsafe directives',()=>{const response=securityHeaders(new Response('ok'));expect(response.headers.get('content-security-policy')).toContain("frame-ancestors 'none'");expect(response.headers.get('content-security-policy')).not.toContain('unsafe-');expect(response.headers.get('x-content-type-options')).toBe('nosniff');expect(response.headers.get('referrer-policy')).toBe('no-referrer');expect(response.headers.get('permissions-policy')).toContain('camera=()');expect(response.headers.get('strict-transport-security')).toContain('63072000');expect(response.headers.get('x-frame-options')).toBe('DENY');});
  it('recursively redacts credentials while preserving safe values',()=>{expect(redact({authorization:'Bearer x',nested:{tokenHash:'x',record:'safe'},list:[{secret:'x'}]})).toEqual({authorization:'[REDACTED]',nested:{tokenHash:'[REDACTED]',record:'safe'},list:[{secret:'[REDACTED]'}]});expect(redact('safe')).toBe('safe');});
});
